"""remove value from paymentes

Revision ID: 25aec229b138
Revises: 6803ac8b5828
Create Date: 2026-09-11 12:18:30.509453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25aec229b138'
down_revision: Union[str, Sequence[str], None] = '6803ac8b5828'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'pay_value', schema='core')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('pay_value', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False), schema='core')
    # ### end Alembic commands ###
