"""update customer location relation

Revision ID: 289b1dcc422d
Revises: 4d7f5d131143
Create Date: 2026-09-04 11:00:43.846261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '289b1dcc422d'
down_revision: Union[str, Sequence[str], None] = '4d7f5d131143'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_cities_name_state'), 'cities', schema='core', type_='unique')
    op.create_unique_constraint('uq_cities_name_state', 'cities', ['cit_normalize_name', 'cit_sta_id'], schema='core')
    op.drop_constraint(op.f('customers_cus_external_id_key'), 'customers', schema='core', type_='unique')
    op.drop_constraint(op.f('customers_cus_loc_id_fkey'), 'customers', schema='core', type_='foreignkey')
    op.drop_column('customers', 'cus_external_id', schema='core')
    op.drop_column('customers', 'cus_loc_id', schema='core')
    op.add_column('orders', sa.Column('ord_customer_external_id', sa.String(), nullable=False), schema='core')
    op.add_column('orders', sa.Column('ord_loc_id', sa.Integer(), nullable=False), schema='core')
    op.create_foreign_key(None, 'orders', 'locations', ['ord_loc_id'], ['loc_id'], source_schema='core', referent_schema='core')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', schema='core', type_='foreignkey')
    op.drop_column('orders', 'ord_loc_id', schema='core')
    op.drop_column('orders', 'ord_customer_external_id', schema='core')
    op.add_column('customers', sa.Column('cus_loc_id', sa.INTEGER(), autoincrement=False, nullable=False), schema='core')
    op.add_column('customers', sa.Column('cus_external_id', sa.VARCHAR(), autoincrement=False, nullable=False), schema='core')
    op.create_foreign_key(op.f('customers_cus_loc_id_fkey'), 'customers', 'locations', ['cus_loc_id'], ['loc_id'], source_schema='core', referent_schema='core')
    op.create_unique_constraint(op.f('customers_cus_external_id_key'), 'customers', ['cus_external_id'], schema='core', postgresql_nulls_not_distinct=False)
    op.drop_constraint('uq_cities_name_state', 'cities', schema='core', type_='unique')
    op.create_unique_constraint(op.f('uq_cities_name_state'), 'cities', ['cit_name', 'cit_sta_id'], schema='core', postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
