"""add_normalize_city_name

Revision ID: 4d7f5d131143
Revises: 65df28bdeae2
Create Date: 2026-08-14 09:43:24.243443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d7f5d131143'
down_revision: Union[str, Sequence[str], None] = '65df28bdeae2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cities', sa.Column('cit_normalize_name', sa.String(), nullable=False), schema='core')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cities', 'cit_normalize_name', schema='core')
    # ### end Alembic commands ###
