"""nullable variables orders

Revision ID: 6803ac8b5828
Revises: c7a06b965f56
Create Date: 2026-09-10 10:47:55.857743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6803ac8b5828'
down_revision: Union[str, Sequence[str], None] = 'c7a06b965f56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('ord_external_id', sa.String(), nullable=False), schema='core')
    op.alter_column('orders', 'ord_approved_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               schema='core')
    op.alter_column('orders', 'ord_shipped_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               schema='core')
    op.alter_column('orders', 'ord_delivered_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               schema='core')
    op.drop_constraint(op.f('orders_order_external_id_key'), 'orders', schema='core', type_='unique')
    op.create_unique_constraint(None, 'orders', ['ord_external_id'], schema='core')
    op.drop_column('orders', 'order_external_id', schema='core')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('order_external_id', sa.VARCHAR(), autoincrement=False, nullable=False), schema='core')
    op.drop_constraint(None, 'orders', schema='core', type_='unique')
    op.create_unique_constraint(op.f('orders_order_external_id_key'), 'orders', ['order_external_id'], schema='core', postgresql_nulls_not_distinct=False)
    op.alter_column('orders', 'ord_delivered_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               schema='core')
    op.alter_column('orders', 'ord_shipped_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               schema='core')
    op.alter_column('orders', 'ord_approved_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               schema='core')
    op.drop_column('orders', 'ord_external_id', schema='core')
    # ### end Alembic commands ###
