"""nullable category english name

Revision ID: 77cc6fe75921
Revises: 289b1dcc422d
Create Date: 2026-09-04 14:28:45.224317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77cc6fe75921'
down_revision: Union[str, Sequence[str], None] = '289b1dcc422d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'cat_name_english',
               existing_type=sa.VARCHAR(),
               nullable=True,
               schema='core')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'cat_name_english',
               existing_type=sa.VARCHAR(),
               nullable=False,
               schema='core')
    # ### end Alembic commands ###
