"""reinitial_migration

Revision ID: 8afababec81a
Revises: 
Create Date: 2026-08-12 19:26:58.342668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8afababec81a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('cat_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cat_name', sa.String(), nullable=False),
    sa.Column('cat_name_english', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('cat_id'),
    schema='core'
    )
    op.create_table('states',
    sa.Column('sta_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sta_name', sa.String(), nullable=False),
    sa.Column('sta_uf', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('sta_id'),
    sa.UniqueConstraint('sta_name'),
    sa.UniqueConstraint('sta_uf'),
    schema='core'
    )
    op.create_table('cities',
    sa.Column('cit_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cit_name', sa.String(), nullable=False),
    sa.Column('cit_sta_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cit_sta_id'], ['core.states.sta_id'], ),
    sa.PrimaryKeyConstraint('cit_id'),
    sa.UniqueConstraint('cit_name', 'cit_sta_id', name='uq_cities_name_state'),
    schema='core'
    )
    op.create_table('products',
    sa.Column('pro_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pro_external_id', sa.String(), nullable=False),
    sa.Column('pro_photo_count', sa.Integer(), nullable=False),
    sa.Column('pro_weight', sa.Integer(), nullable=False),
    sa.Column('pro_width', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('pro_height', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('pro_length', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('pro_cat_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pro_cat_id'], ['core.categories.cat_id'], ),
    sa.PrimaryKeyConstraint('pro_id'),
    sa.UniqueConstraint('pro_external_id'),
    schema='core'
    )
    op.create_table('locations',
    sa.Column('loc_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('loc_code_prefix', sa.String(), nullable=False),
    sa.Column('loc_lat', sa.Numeric(precision=10, scale=8), nullable=False),
    sa.Column('loc_lng', sa.Numeric(precision=11, scale=8), nullable=False),
    sa.Column('loc_cit_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['loc_cit_id'], ['core.cities.cit_id'], ),
    sa.PrimaryKeyConstraint('loc_id'),
    schema='core'
    )
    op.create_table('customers',
    sa.Column('cus_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cus_external_id', sa.String(), nullable=False),
    sa.Column('cus_unique_id', sa.String(), nullable=False),
    sa.Column('cus_loc_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cus_loc_id'], ['core.locations.loc_id'], ),
    sa.PrimaryKeyConstraint('cus_id'),
    sa.UniqueConstraint('cus_external_id'),
    sa.UniqueConstraint('cus_unique_id'),
    schema='core'
    )
    op.create_table('sellers',
    sa.Column('sel_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sel_external_id', sa.String(), nullable=False),
    sa.Column('sel_loc_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sel_loc_id'], ['core.locations.loc_id'], ),
    sa.PrimaryKeyConstraint('sel_id'),
    sa.UniqueConstraint('sel_external_id'),
    schema='core'
    )
    op.create_table('orders',
    sa.Column('ord_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_external_id', sa.String(), nullable=False),
    sa.Column('ord_status', sa.Enum('DELIVERED', 'APPROVED', 'CANCELED', 'CREATED', 'INVOICED', 'PROCESSING', 'SHIPPED', 'UNAVAILABLE', name='order_status'), nullable=False),
    sa.Column('ord_purchase_date', sa.DateTime(), nullable=False),
    sa.Column('ord_approved_at', sa.DateTime(), nullable=False),
    sa.Column('ord_shipped_at', sa.DateTime(), nullable=False),
    sa.Column('ord_delivered_at', sa.DateTime(), nullable=False),
    sa.Column('ord_estimated_delivery_date', sa.Date(), nullable=False),
    sa.Column('ord_cus_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ord_cus_id'], ['core.customers.cus_id'], ),
    sa.PrimaryKeyConstraint('ord_id'),
    sa.UniqueConstraint('order_external_id'),
    schema='core'
    )
    op.create_table('order_items',
    sa.Column('ori_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ori_external_id', sa.String(), nullable=False),
    sa.Column('ori_pro_id', sa.Integer(), nullable=False),
    sa.Column('ori_ord_id', sa.Integer(), nullable=False),
    sa.Column('ori_sel_id', sa.Integer(), nullable=False),
    sa.Column('ori_shipment_limit_date', sa.DateTime(), nullable=False),
    sa.Column('ori_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('ori_freight_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['ori_ord_id'], ['core.orders.ord_id'], ),
    sa.ForeignKeyConstraint(['ori_pro_id'], ['core.products.pro_id'], ),
    sa.ForeignKeyConstraint(['ori_sel_id'], ['core.sellers.sel_id'], ),
    sa.PrimaryKeyConstraint('ori_id'),
    sa.UniqueConstraint('ori_external_id'),
    schema='core'
    )
    op.create_table('payments',
    sa.Column('pay_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pay_ord_id', sa.Integer(), nullable=False),
    sa.Column('pay_sequential', sa.Integer(), nullable=False),
    sa.Column('pay_type', sa.Enum('BOLETO', 'CREDIT_CARD', 'DEBIT_CARD', 'NOT_DEFINED', 'VOUCHER', name='payment_type'), nullable=False),
    sa.Column('pay_installments', sa.Integer(), nullable=False),
    sa.Column('pay_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['pay_ord_id'], ['core.orders.ord_id'], ),
    sa.PrimaryKeyConstraint('pay_id'),
    schema='core'
    )
    op.create_table('reviews',
    sa.Column('rev_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rev_external_id', sa.String(), nullable=False),
    sa.Column('rev_ord_id', sa.Integer(), nullable=False),
    sa.Column('rev_score', sa.Integer(), nullable=False),
    sa.Column('rev_title', sa.String(), nullable=False),
    sa.Column('rev_comment', sa.String(), nullable=False),
    sa.Column('rev_creation_at', sa.DateTime(), nullable=False),
    sa.Column('rev_answered_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('rev_score BETWEEN 1 AND 5', name='ck_reviews_score_range'),
    sa.ForeignKeyConstraint(['rev_ord_id'], ['core.orders.ord_id'], ),
    sa.PrimaryKeyConstraint('rev_id'),
    sa.UniqueConstraint('rev_external_id'),
    schema='core'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews', schema='core')
    op.drop_table('payments', schema='core')
    op.drop_table('order_items', schema='core')
    op.drop_table('orders', schema='core')
    op.drop_table('sellers', schema='core')
    op.drop_table('customers', schema='core')
    op.drop_table('locations', schema='core')
    op.drop_table('products', schema='core')
    op.drop_table('cities', schema='core')
    op.drop_table('states', schema='core')
    op.drop_table('categories', schema='core')
    # ### end Alembic commands ###
