"""nullable varible review

Revision ID: 99b1e41bbe06
Revises: 25aec229b138
Create Date: 2026-09-11 12:48:44.733694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '99b1e41bbe06'
down_revision: Union[str, Sequence[str], None] = '25aec229b138'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reviews', 'rev_title',
               existing_type=sa.VARCHAR(),
               nullable=True,
               schema='core')
    op.alter_column('reviews', 'rev_comment',
               existing_type=sa.VARCHAR(),
               nullable=True,
               schema='core')
    op.alter_column('reviews', 'rev_answered_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               schema='core')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reviews', 'rev_answered_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               schema='core')
    op.alter_column('reviews', 'rev_comment',
               existing_type=sa.VARCHAR(),
               nullable=False,
               schema='core')
    op.alter_column('reviews', 'rev_title',
               existing_type=sa.VARCHAR(),
               nullable=False,
               schema='core')
    # ### end Alembic commands ###
