"""create customers table

Revision ID: 14642a0e0573
Revises: d5025c03c23d
Create Date: 2026-08-05 13:12:58.926356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14642a0e0573'
down_revision: Union[str, Sequence[str], None] = 'd5025c03c23d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('cus_id', sa.String(), nullable=False),
    sa.Column('cus_unique_id', sa.String(), nullable=False),
    sa.Column('cus_loc_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['cus_loc_id'], ['core.locations.loc_id'], ),
    sa.PrimaryKeyConstraint('cus_id'),
    sa.UniqueConstraint('cus_unique_id'),
    schema='core'
    )
    op.create_foreign_key(None, 'cities', 'states', ['cit_sta_id'], ['sta_id'], source_schema='core', referent_schema='core')
    op.create_foreign_key(None, 'locations', 'cities', ['loc_cit_id'], ['cit_id'], source_schema='core', referent_schema='core')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'locations', schema='core', type_='foreignkey')
    op.drop_constraint(None, 'cities', schema='core', type_='foreignkey')
    op.drop_table('customers', schema='core')
    # ### end Alembic commands ###
