"""create_reviews_table

Revision ID: 246a3a2de1a4
Revises: 9978381facc5
Create Date: 2026-08-11 10:08:39.145664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '246a3a2de1a4'
down_revision: Union[str, Sequence[str], None] = '9978381facc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('rev_id', sa.String(), nullable=False),
    sa.Column('rev_ord_id', sa.String(), nullable=False),
    sa.Column('rev_score', sa.Integer(), nullable=False),
    sa.Column('rev_title', sa.String(), nullable=False),
    sa.Column('rev_comment', sa.String(), nullable=False),
    sa.Column('rev_creation_at', sa.DateTime(), nullable=False),
    sa.Column('rev_answered_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['rev_ord_id'], ['core.orders.ord_id'], ),
    sa.PrimaryKeyConstraint('rev_id'),
    schema='core'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews', schema='core')
    # ### end Alembic commands ###
