"""create state table

Revision ID: 69801360378e
Revises: 
Create Date: 2026-08-05 12:28:24.132249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69801360378e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('states',
    sa.Column('sta_id', sa.String(), nullable=False),
    sa.Column('sta_name', sa.String(), nullable=False),
    sa.Column('sta_uf', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('sta_id'),
    sa.UniqueConstraint('sta_name'),
    sa.UniqueConstraint('sta_uf'),
    schema='core'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('states', schema='core')
    # ### end Alembic commands ###
