"""create_categories_table

Revision ID: 69f3ea1f3f1a
Revises: 6fbb2acd97f4
Create Date: 2026-08-11 09:59:22.219423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69f3ea1f3f1a'
down_revision: Union[str, Sequence[str], None] = '6fbb2acd97f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('cat_name', sa.String(), nullable=False),
    sa.Column('cat_name_english', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('cat_name'),
    sa.UniqueConstraint('cat_name_english'),
    schema='core'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('categories', schema='core')
    # ### end Alembic commands ###
