"""create_sellers_table

Revision ID: 6fbb2acd97f4
Revises: 14642a0e0573
Create Date: 2026-08-11 09:55:39.270256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fbb2acd97f4'
down_revision: Union[str, Sequence[str], None] = '14642a0e0573'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sellers',
    sa.Column('sel_id', sa.String(), nullable=False),
    sa.Column('sel_loc_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['sel_loc_id'], ['core.locations.loc_id'], ),
    sa.PrimaryKeyConstraint('sel_id'),
    schema='core'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sellers', schema='core')
    # ### end Alembic commands ###
