"""apply_database_rules

Revision ID: 72c8a49a6f0b
Revises: 246a3a2de1a4
Create Date: 2026-08-11 10:50:14.501938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72c8a49a6f0b'
down_revision: Union[str, Sequence[str], None] = '246a3a2de1a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

order_status = sa.Enum(
    "delivered",
    "approved",
    "canceled",
    "created",
    "invoiced",
    "processing",
    "shipped",
    "unavailable",
    name="order_status"
)

payment_type = sa.Enum(
    "boleto",
    "credit_card",
    "debit_card",
    "not_defined",
    "voucher",
    name="payment_type"
)


def upgrade() -> None:
    """Upgrade schema."""
    order_status.create(op.get_bind(), checkfirst=True)
    payment_type.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('locations', 'loc_lat',
               existing_type=sa.VARCHAR(),
               type_=sa.Numeric(precision=10, scale=8),
               existing_nullable=False,
               postgresql_using='loc_lat::numeric(10,8)',
               schema='core')
    op.alter_column('locations', 'loc_lng',
               existing_type=sa.VARCHAR(),
               type_=sa.Numeric(precision=11, scale=8),
               existing_nullable=False,
               postgresql_using='loc_lng::numeric(11,8)',
               schema='core')
    op.alter_column('order_items', 'ori_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False,
               schema='core')
    op.alter_column('order_items', 'ori_freight_value',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False,
               schema='core')
    op.alter_column('orders', 'ord_status',
               existing_type=sa.VARCHAR(),
               type_=order_status,
               existing_nullable=False,
               postgresql_using='ord_status::text::order_status',
               schema='core')
    op.add_column('payments', sa.Column('pay_sequential', sa.Integer(), nullable=False), schema='core')
    op.alter_column('payments', 'pay_type',
               existing_type=sa.VARCHAR(),
               type_=payment_type,
               existing_nullable=False,
               postgresql_using='pay_type::text::payment_type',
               schema='core')
    op.alter_column('payments', 'pay_value',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False,
               schema='core')
    op.alter_column('products', 'pro_width',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=8, scale=2),
               existing_nullable=False,
               schema='core')
    op.alter_column('products', 'pro_height',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=8, scale=2),
               existing_nullable=False,
               schema='core')
    op.alter_column('products', 'pro_length',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=8, scale=2),
               existing_nullable=False,
               schema='core')
    op.create_check_constraint('ck_reviews_score_range', 'reviews', 'rev_score BETWEEN 1 AND 5', schema='core')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_reviews_score_range', 'reviews', schema='core', type_='check')
    op.alter_column('products', 'pro_length',
               existing_type=sa.Numeric(precision=8, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False,
               schema='core')
    op.alter_column('products', 'pro_height',
               existing_type=sa.Numeric(precision=8, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False,
               schema='core')
    op.alter_column('products', 'pro_width',
               existing_type=sa.Numeric(precision=8, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False,
               schema='core')
    op.alter_column('payments', 'pay_value',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False,
               schema='core')
    op.alter_column('payments', 'pay_type',
               existing_type=payment_type,
               type_=sa.VARCHAR(),
               existing_nullable=False,
               schema='core')
    op.drop_column('payments', 'pay_sequential', schema='core')
    op.alter_column('orders', 'ord_status',
               existing_type=order_status,
               type_=sa.VARCHAR(),
               existing_nullable=False,
               schema='core')
    op.alter_column('order_items', 'ori_freight_value',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False,
               schema='core')
    op.alter_column('order_items', 'ori_price',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False,
               schema='core')
    op.alter_column('locations', 'loc_lng',
               existing_type=sa.Numeric(precision=11, scale=8),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               schema='core')
    op.alter_column('locations', 'loc_lat',
               existing_type=sa.Numeric(precision=10, scale=8),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               schema='core')
    # ### end Alembic commands ###
