"""create_orders_table

Revision ID: 808dde9d1c10
Revises: 84d748f931a0
Create Date: 2026-08-11 10:03:26.065588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '808dde9d1c10'
down_revision: Union[str, Sequence[str], None] = '84d748f931a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('ord_id', sa.String(), nullable=False),
    sa.Column('ord_status', sa.String(), nullable=False),
    sa.Column('ord_purchase_date', sa.DateTime(), nullable=False),
    sa.Column('ord_approved_at', sa.DateTime(), nullable=False),
    sa.Column('ord_shipped_at', sa.DateTime(), nullable=False),
    sa.Column('ord_delivered_at', sa.DateTime(), nullable=False),
    sa.Column('ord_estimated_delivery_date', sa.Date(), nullable=False),
    sa.Column('ord_cus_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['ord_cus_id'], ['core.customers.cus_id'], ),
    sa.PrimaryKeyConstraint('ord_id'),
    schema='core'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders', schema='core')
    # ### end Alembic commands ###
