"""create_products_table

Revision ID: 84d748f931a0
Revises: 69f3ea1f3f1a
Create Date: 2026-08-11 10:00:34.191606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84d748f931a0'
down_revision: Union[str, Sequence[str], None] = '69f3ea1f3f1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('pro_id', sa.String(), nullable=False),
    sa.Column('pro_photo_count', sa.Integer(), nullable=False),
    sa.Column('pro_weight', sa.Integer(), nullable=False),
    sa.Column('pro_width', sa.Float(), nullable=False),
    sa.Column('pro_height', sa.Float(), nullable=False),
    sa.Column('pro_length', sa.Float(), nullable=False),
    sa.Column('pro_cat_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['pro_cat_name'], ['core.categories.cat_name'], ),
    sa.PrimaryKeyConstraint('pro_id'),
    schema='core'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products', schema='core')
    # ### end Alembic commands ###
