"""create cities table

Revision ID: 8deaf3785b26
Revises: 69801360378e
Create Date: 2026-08-05 12:35:30.378761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8deaf3785b26'
down_revision: Union[str, Sequence[str], None] = '69801360378e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cities',
    sa.Column('cit_id', sa.String(), nullable=False),
    sa.Column('cit_name', sa.String(), nullable=False),
    sa.Column('cit_sta_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('cit_id'),
    sa.UniqueConstraint('cit_name', 'cit_sta_id', name='uq_cities_name_state'),
    schema='core'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cities', schema='core')
    # ### end Alembic commands ###
