"""create_payments_table

Revision ID: 9978381facc5
Revises: cbf3d670daac
Create Date: 2026-08-11 10:06:57.956334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9978381facc5'
down_revision: Union[str, Sequence[str], None] = 'cbf3d670daac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('pay_id', sa.String(), nullable=False),
    sa.Column('pay_ord_id', sa.String(), nullable=False),
    sa.Column('pay_type', sa.String(), nullable=False),
    sa.Column('pay_installments', sa.Integer(), nullable=False),
    sa.Column('pay_value', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['pay_ord_id'], ['core.orders.ord_id'], ),
    sa.PrimaryKeyConstraint('pay_id'),
    schema='core'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments', schema='core')
    # ### end Alembic commands ###
