"""create_order_items_table

Revision ID: cbf3d670daac
Revises: 808dde9d1c10
Create Date: 2026-08-11 10:05:41.937172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbf3d670daac'
down_revision: Union[str, Sequence[str], None] = '808dde9d1c10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_items',
    sa.Column('ori_id', sa.String(), nullable=False),
    sa.Column('ori_pro_id', sa.String(), nullable=False),
    sa.Column('ori_ord_id', sa.String(), nullable=False),
    sa.Column('ori_sel_id', sa.String(), nullable=False),
    sa.Column('ori_shipment_limit_date', sa.DateTime(), nullable=False),
    sa.Column('ori_price', sa.Float(), nullable=False),
    sa.Column('ori_freight_value', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['ori_ord_id'], ['core.orders.ord_id'], ),
    sa.ForeignKeyConstraint(['ori_pro_id'], ['core.products.pro_id'], ),
    sa.ForeignKeyConstraint(['ori_sel_id'], ['core.sellers.sel_id'], ),
    sa.PrimaryKeyConstraint('ori_id'),
    schema='core'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_items', schema='core')
    # ### end Alembic commands ###
