#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" \
  -v MIGRATION_USER="$MIGRATION_USER" \
  -v MIGRATION_PASSWORD="$MIGRATION_PASSWORD" \
  -v API_USER="$API_USER" \
  -v API_PASSWORD="$API_PASSWORD" \
  -v POSTGRES_DB="$POSTGRES_DB" <<-EOSQL
CREATE USER :MIGRATION_USER
WITH PASSWORD :'MIGRATION_PASSWORD';

GRANT CONNECT ON DATABASE :POSTGRES_DB
TO :MIGRATION_USER;

GRANT USAGE, CREATE
ON SCHEMA public, core, staging, analytics
TO :MIGRATION_USER;

CREATE USER :API_USER
WITH PASSWORD :'API_PASSWORD';

GRANT CONNECT ON DATABASE :POSTGRES_DB
TO :API_USER;

GRANT USAGE
ON SCHEMA core, staging, analytics
TO :API_USER;

GRANT SELECT, INSERT, UPDATE, DELETE
ON ALL TABLES IN SCHEMA core, staging, analytics
TO :API_USER;

ALTER DEFAULT PRIVILEGES FOR ROLE :MIGRATION_USER
IN SCHEMA core, staging, analytics
GRANT SELECT, INSERT, UPDATE, DELETE
ON TABLES
TO :API_USER;

GRANT USAGE, SELECT
ON ALL SEQUENCES IN SCHEMA core, staging, analytics
TO :API_USER;

ALTER DEFAULT PRIVILEGES FOR ROLE :MIGRATION_USER
IN SCHEMA core, staging, analytics
GRANT USAGE, SELECT
ON SEQUENCES
TO :API_USER;
EOSQL